const citiesDasta = [
  {
    name: "Karachi",
    province: "Sindh",
    population: 16000000,
    area: 591,
    famousFor: ["Sea", "Port", "Diversity"],
  },
  {
    name: "Lahore",
    province: "Punjab",
    population: 11000000,
    area: 1772,
    famousFor: ["Culture", "Food", "History"],
  },
  {
    name: "Islamabad",
    province: "Islamabad",
    population: 1000000,
    area: 906,
    famousFor: ["Greenery", "Modernity"],
  },
  {
    name: "Peshawar",
    province: "Khyber Pakhtunkhwa",
    population: 2000000,
    area: 1257,
    famousFor: ["History", "Pashto Culture"],
  },
  {
    name: "Quetta",
    province: "Balochistan",
    population: 1000000,
    area: 2653,
    famousFor: ["Dry Fruits", "Culture"],
  },
  {
    name: "Faisalabad",
    province: "Punjab",
    population: 3000000,
    area: 1200,
    famousFor: ["Textile Industry"],
  },
  {
    name: "Multan",
    province: "Punjab",
    population: 2000000,
    area: 3721,
    famousFor: ["Sufi Shrines", "Mangoes"],
  },
  {
    name: "Rawalpindi",
    province: "Punjab",
    population: 2000000,
    area: 1500,
    famousFor: ["Military", "Markets"],
  },
  {
    name: "Gujranwala",
    province: "Punjab",
    population: 2000000,
    area: 3600,
    famousFor: ["Cuisine", "Pottery"],
  },
  {
    name: "Sialkot",
    province: "Punjab",
    population: 1000000,
    area: 3162,
    famousFor: ["Sports Goods"],
  },
  {
    name: "Hyderabad",
    province: "Sindh",
    population: 1700000,
    area: 91,
    famousFor: ["Culture", "Historic Sites"],
  },
  {
    name: "Bahawalpur",
    province: "Punjab",
    population: 800000,
    area: 1242,
    famousFor: ["Architecture", "Sufism"],
  },
  {
    name: "Sukkur",
    province: "Sindh",
    population: 500000,
    area: 193,
    famousFor: ["Sukkur Barrage"],
  },
  {
    name: "Larkana",
    province: "Sindh",
    population: 450000,
    area: 160,
    famousFor: ["Sindh Culture", "Historical Sites"],
  },
  {
    name: "Mardan",
    province: "Khyber Pakhtunkhwa",
    population: 300000,
    area: 250,
    famousFor: ["Cultural Heritage"],
  },
  {
    name: "Abbottabad",
    province: "Khyber Pakhtunkhwa",
    population: 400000,
    area: 300,
    famousFor: ["Tourism", "Natural Beauty"],
  },
  {
    name: "Mirpur",
    province: "Azad Kashmir",
    population: 150000,
    area: 80,
    famousFor: ["Tourism", "Cultural Diversity"],
  },
  {
    name: "Gujrat",
    province: "Punjab",
    population: 300000,
    area: 3,
    famousFor: ["Ceramics", "Culture"],
  },
  {
    name: "Jhang",
    province: "Punjab",
    population: 400000,
    area: 3,
    famousFor: ["Agriculture", "Culture"],
  },
  {
    name: "Kasur",
    province: "Punjab",
    population: 200000,
    area: 1,
    famousFor: ["Sufi Culture", "Mangoes"],
  },
  {
    name: "Dera Ghazi Khan",
    province: "Punjab",
    population: 300000,
    area: 8,
    famousFor: ["Agriculture", "Culture"],
  },
  {
    name: "Sargodha",
    province: "Punjab",
    population: 600000,
    area: 6,
    famousFor: ["Oranges", "Agriculture"],
  },
  {
    name: "Kotli",
    province: "Azad Kashmir",
    population: 250000,
    area: 45,
    famousFor: ["Cultural Heritage"],
  },
  {
    name: "Attock",
    province: "Punjab",
    population: 200000,
    area: 5,
    famousFor: ["Historic Sites"],
  },
  {
    name: "Chiniot",
    province: "Punjab",
    population: 250000,
    area: 4,
    famousFor: ["Furniture", "Woodwork"],
  },
];
const citiesData = citiesDasta.map((city) => city.name);

export default citiesData;
